on:
  push:
    branches:
      - main

env:
  NOMAD_ADDR: https://nomad-ui.internal.demophoon.com

jobs:
  prod-home:
    runs-on: docker
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7
        with:
          ref: main
          show-progress: true
      - id: prod-home
        uses: ./.forgejo/actions/dispatch-terraform
        with:
          workspace: prod-home
      - id: nomad-cascadia
        uses: ./.forgejo/actions/dispatch-terraform
        with:
          workspace: nomad-cascadia
      - id: renovate
        uses: ./.forgejo/actions/renovate
