log:
  level: info

runner:
  file: /data/.runner
  capacity: 1
  timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  labels:
    - "ci:host"
    - "ubuntu:docker://ubuntu:26.04"
    - "docker:docker://registry.services.demophoon.com/demophoon/dispatcher:dc15fa0-1775855159"

  envs:
    DOCKER_HOST: tcp://dind.docker.internal:2375

cache:
  enabled: true
  dir: /data/cache

container:
  network: host
  privileged: true
  valid_volumes:
    - /usr/local/share/ca-certificates
  docker_host: 'tcp://10.0.2.15:2376'
  options: '--add-host=dind.docker.internal:host-gateway'

server:
  connections:
    brittg:
      url: https://git.brittg.com/
