---
arch_map:
  x86_64: amd64
  aarch64: arm64

install_miren: true
miren_version: "v0.10.0"
miren_release_base_url: "https://api.miren.cloud/assets/release/miren"

cni_plugins_version: "1.0.0"

runner_packages:
  - openssh-server
  - qemu-guest-agent
  - vault=1.21.4-1
  - nomad=1.11.2-1
  - consul=1.22.5-1
  - tailscale
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  - nfs-common
  - dnsmasq
  - jq
  - curl
  - git
