---
- name: Start Docker-in-Docker (DinD) container
  docker_container:
    name: dind
    image: docker:dind
    state: started
    restart_policy: always
    privileged: true
    ports:
      - "2376:2375"
    command:
      - "dockerd"
      - "-H"
      - "tcp://0.0.0.0:2375"
      - "--tls=false"
