name: 'Run Renovate'
author: 'Britt Gresham'
description: |
  This action dispatches a Nomad job that runs Renovate to update dependencies.

runs:
  using: 'composite'
  steps:
    - name: 'Run Renovate'
      run: |
        nomad job periodic force renovate | tee nomad.output
