name: 'Dispatch Terraform Apply Job'
author: 'Britt Gresham'
description: |
  This action dispatches a Nomad job that applies terraform changes.
  This action will wait until the job is complete before finishing.

inputs:
  workspace:
    description: 'The workspace to run the terraform apply in'

runs:
  using: 'composite'
  steps:
    - name: 'Dispatch ${{ inputs.workspace }}'
      run: |
        nomad job dispatch -meta APPLY_WORKSPACE=${{ inputs.workspace }} infrastructure-maintenance-terraform | tee nomad.output
        while true; do
          STATUS=$(nomad job status --short $(grep 'Dispatched Job ID' nomad.output | awk '{print $5}') | grep Status | awk '{print $3}')
          if [[ "$STATUS" == "dead" ]]; then
            echo "Job completed successfully."
            break
          elif [[ "$STATUS" == "running" ]]; then
            echo "Current status: $STATUS. Waiting for completion..."
            sleep 10
          else
            echo "Job failed."
            exit 1
          fi
        done
