---
- name: Configure Forgejo runner VM
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars_files:
    - vars/runner.yml

  tasks:
    - name: Run bootstrap tasks
      ansible.builtin.import_tasks: tasks/bootstrap.yml

    - name: Run repository tasks
      ansible.builtin.import_tasks: tasks/repos.yml

    - name: Run user setup tasks
      ansible.builtin.import_tasks: tasks/users.yml

    - name: Run package tasks
      ansible.builtin.import_tasks: tasks/packages.yml

    - name: Run configuration tasks
      ansible.builtin.import_tasks: tasks/config.yml

    - name: Run DIND container
      ansible.builtin.import_tasks: tasks/dind.yml

    - name: Run Forgejo runner installation tasks
      ansible.builtin.import_tasks: tasks/forgejo_runner.yml

    - name: Run CNI installation tasks
      ansible.builtin.import_tasks: tasks/cni.yml

    - name: Run optional Miren installation tasks
      ansible.builtin.import_tasks: tasks/miren.yml

    - name: Run finalization tasks
      ansible.builtin.import_tasks: tasks/finalize.yml
